version: "2.1"
services:

  container1:
    container_name: service-a
    build:
      context: ./service-a
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True

  container2:
    container_name: service-a
    build:
      context: ./service-a
    ports:
      - "5001:5000"
    environment:
      - DEBUG=True